app = "igensys"  # You can change this name if Fly complains it's taken
primary_region = "sin"  # SIN = Singapore, good for Pakistan region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
